/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utp.aed.proyectotorneo.view;

/**
 *
 * @author MSI
 */
public class Inicio extends javax.swing.JFrame {

    public static String campeonActual = "";
    public static com.utp.aed.proyectotorneo.estructuras.ListaEnlazadaEquipos listaEquipos = new com.utp.aed.proyectotorneo.estructuras.ListaEnlazadaEquipos();
    
    private com.utp.aed.proyectotorneo.model.Usuario usuarioActual;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setSize(1000, 700);
        this.setLocationRelativeTo(null);
    }
    
    public Inicio(com.utp.aed.proyectotorneo.model.Usuario usuario) {
        this();
        this.usuarioActual = usuario;
        
        
        if (usuarioActual != null && "Equipo".equalsIgnoreCase(usuarioActual.getRol().getNombre())) {
            btnIns.setVisible(false);
            btnConfig.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnIns = new javax.swing.JButton();
        btnLlaves = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSidebar.setBackground(new java.awt.Color(33, 37, 41));
        pnlSidebar.setLayout(new java.awt.GridLayout(5, 1));

        btnDashboard.setBackground(new java.awt.Color(0, 0, 0));
        btnDashboard.setForeground(new java.awt.Color(204, 204, 204));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnDashboard);

        btnIns.setBackground(new java.awt.Color(0, 0, 0));
        btnIns.setForeground(new java.awt.Color(204, 204, 204));
        btnIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_inscripcion.png"))); // NOI18N
        btnIns.setText("Inscripción");
        btnIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnIns);

        btnLlaves.setBackground(new java.awt.Color(0, 0, 0));
        btnLlaves.setForeground(new java.awt.Color(204, 204, 204));
        btnLlaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_torneo.png"))); // NOI18N
        btnLlaves.setText("Ver Torneo");
        btnLlaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlavesActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnLlaves);

        btnConfig.setBackground(new java.awt.Color(0, 0, 0));
        btnConfig.setForeground(new java.awt.Color(204, 204, 204));
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_configuracion.png"))); // NOI18N
        btnConfig.setText("Configuración");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnConfig);

        btncerrar.setBackground(new java.awt.Color(255, 51, 51));
        btncerrar.setForeground(new java.awt.Color(204, 204, 204));
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_cerrar.png"))); // NOI18N
        btncerrar.setText("Cerrar Sesion");
        btncerrar.setOpaque(true);
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        pnlSidebar.add(btncerrar);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.WEST);

        pnlContenido.setBackground(new java.awt.Color(0, 0, 0));
        pnlContenido.setForeground(new java.awt.Color(255, 255, 255));
        pnlContenido.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        PanelDashboard pnlDash = new PanelDashboard(this.usuarioActual);
        pnlContenido.removeAll();
        pnlContenido.add(pnlDash, java.awt.BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsActionPerformed
        PanelInscripcion pnlIns = new PanelInscripcion();
        pnlContenido.removeAll();
        pnlContenido.add(pnlIns, java.awt.BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }//GEN-LAST:event_btnInsActionPerformed

    private void btnLlavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlavesActionPerformed
        PanelLlaves pnlLlav = new PanelLlaves(this.usuarioActual);
        pnlContenido.removeAll();
        pnlContenido.add(pnlLlav, java.awt.BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }//GEN-LAST:event_btnLlavesActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
        PanelConfiguracion pnlConfig = new PanelConfiguracion();
        pnlContenido.removeAll();
        pnlContenido.add(pnlConfig, java.awt.BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        this.dispose();
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_btncerrarActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
public void irAPanelLlaves() {
        PanelLlaves pnlLlav = new PanelLlaves(this.usuarioActual);
        pnlContenido.removeAll();
        pnlContenido.add(pnlLlav, java.awt.BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnIns;
    private javax.swing.JButton btnLlaves;
    private javax.swing.JButton btncerrar;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlSidebar;
    // End of variables declaration//GEN-END:variables
}
