/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utp.aed.proyectotorneo.view;

/**
 *
 * @author MSI
 */
public class PanelLlaves extends javax.swing.JPanel {


    private com.utp.aed.proyectotorneo.model.NodoPartido partidoFinal;

    private javax.swing.tree.DefaultMutableTreeNode crearNodoVisual(com.utp.aed.proyectotorneo.model.NodoPartido partido) {
        if (partido == null) return null;

        String titulo = partido.ganador.equals("Pendiente") ? 
                        partido.equipo1 + " VS " + partido.equipo2 : 
                        "🏆 " + partido.ganador;

        NodoTorneo nodoVisual = new NodoTorneo(titulo, partido);

        if (partido.partidoPrevio1 != null) nodoVisual.add(crearNodoVisual(partido.partidoPrevio1));
        if (partido.partidoPrevio2 != null) nodoVisual.add(crearNodoVisual(partido.partidoPrevio2));

        return nodoVisual;
    }

    /**
     * Creates new form PanelLlaves
     */
    public PanelLlaves() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerarTorneo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbolTorneo = new javax.swing.JTree();
        btnFinalizado = new javax.swing.JButton();

        setBackground(new java.awt.Color(37, 37, 38));

        btnGenerarTorneo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnGenerarTorneo.setText("Generar Emparejamientos");
        btnGenerarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTorneoActionPerformed(evt);
            }
        });

        arbolTorneo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        arbolTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolTorneoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(arbolTorneo);

        btnFinalizado.setText("🏆 Torneo Finalizado");
        btnFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerarTorneo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizado)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarTorneo)
                    .addComponent(btnFinalizado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTorneoActionPerformed
        java.util.ArrayList<com.utp.aed.proyectotorneo.model.NodoPartido> rondaActual = new java.util.ArrayList<>();
        
        for (int i = 0; i < Inicio.listaEquipos.size(); i += 2) {
            String eq1 = Inicio.listaEquipos.get(i);
            String eq2 = (i + 1 < Inicio.listaEquipos.size()) ? Inicio.listaEquipos.get(i + 1) : "Pase Directo";
            rondaActual.add(new com.utp.aed.proyectotorneo.model.NodoPartido(eq1, eq2));
        }
        while (rondaActual.size() > 1) {
            java.util.ArrayList<com.utp.aed.proyectotorneo.model.NodoPartido> siguienteRonda = new java.util.ArrayList<>();
            for (int i = 0; i < rondaActual.size(); i += 2) {
                com.utp.aed.proyectotorneo.model.NodoPartido p1 = rondaActual.get(i);
                com.utp.aed.proyectotorneo.model.NodoPartido p2 = (i + 1 < rondaActual.size()) ? rondaActual.get(i + 1) : new com.utp.aed.proyectotorneo.model.NodoPartido("Pase Directo", "Pase Directo");
                siguienteRonda.add(new com.utp.aed.proyectotorneo.model.NodoPartido(p1, p2));
            }
            rondaActual = siguienteRonda;
        }
        if (!rondaActual.isEmpty()) {
            partidoFinal = rondaActual.get(0);
            javax.swing.tree.DefaultMutableTreeNode raizVisual = crearNodoVisual(partidoFinal);
            arbolTorneo.setModel(new javax.swing.tree.DefaultTreeModel(raizVisual));
            
            for (int i = 0; i < arbolTorneo.getRowCount(); i++) {
                arbolTorneo.expandRow(i);
            }
            btnGenerarTorneo.setEnabled(false);
        }


    }//GEN-LAST:event_btnGenerarTorneoActionPerformed

    private void arbolTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolTorneoMouseClicked
    if (evt.getClickCount() == 2) {
            NodoTorneo nodoVisual = (NodoTorneo) arbolTorneo.getLastSelectedPathComponent();
            if (nodoVisual == null) return;

            com.utp.aed.proyectotorneo.model.NodoPartido partidoLogico = nodoVisual.partidoLogico;

            if (partidoLogico.ganador.equals("Pendiente") && !partidoLogico.equipo1.equals("Esperando rival") && !partidoLogico.equipo2.equals("Esperando rival")) {
                
                String[] opciones = {partidoLogico.equipo1, partidoLogico.equipo2};
                int eleccion = javax.swing.JOptionPane.showOptionDialog(this, "¿Quién ganó este partido?", "Resultado", javax.swing.JOptionPane.DEFAULT_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

                if (eleccion >= 0) {
                    String ganador = opciones[eleccion];
                    partidoLogico.ganador = ganador;

                    NodoTorneo padreVisual = (NodoTorneo) nodoVisual.getParent();
                    if(padreVisual != null){
                         com.utp.aed.proyectotorneo.model.NodoPartido partidoPadre = padreVisual.partidoLogico;
                         if(partidoPadre.partidoPrevio1 == partidoLogico) partidoPadre.equipo1 = ganador;
                         else partidoPadre.equipo2 = ganador;
                    } else {
                         btnFinalizado.setVisible(true); 
                         Inicio.campeonActual = ganador;
                         javax.swing.JOptionPane.showMessageDialog(this, "¡EL CAMPEÓN ES: " + ganador + "!", "FIN DEL TORNEO", javax.swing.JOptionPane.WARNING_MESSAGE);
                    }

                    arbolTorneo.setModel(new javax.swing.tree.DefaultTreeModel(crearNodoVisual(partidoFinal)));
                    for (int i = 0; i < arbolTorneo.getRowCount(); i++) arbolTorneo.expandRow(i);
                }
            }
        }
    }//GEN-LAST:event_arbolTorneoMouseClicked

    private void btnFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolTorneo;
    private javax.swing.JButton btnFinalizado;
    private javax.swing.JButton btnGenerarTorneo;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    // Clase especial para guardar la info sin romper el texto de la pantalla
    class NodoTorneo extends javax.swing.tree.DefaultMutableTreeNode {
        public com.utp.aed.proyectotorneo.model.NodoPartido partidoLogico;
        
        public NodoTorneo(String texto, com.utp.aed.proyectotorneo.model.NodoPartido partido) {
            super(texto); // Esto le dice a Java exactamente qué texto mostrar en pantalla
            this.partidoLogico = partido; // Aquí escondemos los datos de forma segura
        }
    }
}


