/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utp.aed.proyectotorneo.view;

/**
 *
 * @author MSI
 */
public class PanelInscripcion extends javax.swing.JPanel {

    private PilaEquipos pilaDeshacer = new PilaEquipos();
    private PilaPapelera papeleraReciclaje = new PilaPapelera();

    public PanelInscripcion() {
        initComponents();

        javax.swing.JButton btnOrdenar = new javax.swing.JButton("Ordenar (A-Z)");
        btnOrdenar.addActionListener(e -> {
            Inicio.listaEquipos.ordenarBurbujaAlfabeticamente();
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaEquipos.getModel();
            modelo.setRowCount(0);
            for (int i = 0; i < Inicio.listaEquipos.getTamano(); i++) {
                modelo.addRow(new Object[]{Inicio.listaEquipos.obtener(i)});
            }
        });
        jPanel1.add(btnOrdenar);

        actualizarPantalla();
    }

    private void actualizarPantalla() {
        com.utp.aed.proyectotorneo.dao.EquipoDAO dao = new com.utp.aed.proyectotorneo.dao.EquipoDAO();
        java.util.List<String> equiposDB = dao.obtenerTodosLosNombres();
        Inicio.listaEquipos.limpiar();
        for (String eq : equiposDB) {
            Inicio.listaEquipos.insertar(eq);
        }

        int total = Inicio.listaEquipos.getTamano();
        lblTotalInscritos.setText(String.valueOf(total));

        btnReiniciar.setVisible(total > 0);
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaEquipos.getModel();
        modelo.setRowCount(0);
        for (int i = 0; i < Inicio.listaEquipos.getTamano(); i++) {
            modelo.addRow(new Object[]{Inicio.listaEquipos.obtener(i)});
        }
        if (total >= 2) {
            btnGenerarLlaves.setEnabled(true);
        } else {
            btnGenerarLlaves.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreEquipo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalInscritos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGenerarLlaves = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        btnReiniciar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_inscripcion.png"))); // NOI18N
        jLabel2.setText("Módulo de Inscripción ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 12, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Gestión de los equipos que participarán en el torneo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_registro.png"))); // NOI18N
        jLabel1.setText("REGISTRO DE EQUIPOS");

        jLabel4.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 14)); // NOI18N
        jLabel4.setText("Nombre del equipo");

        txtNombreEquipo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEquipoActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Rossanova Personal Use Light", 0, 14)); // NOI18N
        btnAgregar.setText("+ Agregar Equipo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(30, 30, 30))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 85, -1, 170));

        jLabel5.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_torneo1.png"))); // NOI18N
        jLabel5.setText("Validación del Torneo");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Total de Equipos: ");

        lblTotalInscritos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalInscritos.setText("0");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 246, 248));
        jLabel7.setText("Formato Eliminatorio");

        btnGenerarLlaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_generar.png"))); // NOI18N
        btnGenerarLlaves.setText("Generar Llaves del Torneo");
        btnGenerarLlaves.setEnabled(false);
        btnGenerarLlaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarLlavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addComponent(lblTotalInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGenerarLlaves))
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalInscritos))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarLlaves)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_inscripcion.png"))); // NOI18N
        jLabel8.setText("Lista De Equipos Inscritos");

        tablaEquipos.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "EQUIPOS"
            }
        ));
        jScrollPane1.setViewportView(tablaEquipos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 85, 390, 480));

        btnReiniciar.setBackground(new java.awt.Color(255, 51, 51));
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar.setText("Reiniciar Torneo");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 28, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Rossanova Personal Use Light", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 120, -1));

        btnDeshacer.setFont(new java.awt.Font("Rossanova Personal Use Light", 0, 12)); // NOI18N
        btnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_deshacer.png"))); // NOI18N
        btnDeshacer.setText("Deshacer");
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });
        add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 130, -1));

        btnRestaurar.setFont(new java.awt.Font("Rossanova Personal Use Light", 0, 12)); // NOI18N
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_restaurar.png"))); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });
        add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        btnOrdenar.setFont(new java.awt.Font("Rossanova Personal Use Light", 0, 12)); // NOI18N
        btnOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_ordenar.png"))); // NOI18N
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoLogin.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2320, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarLlavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarLlavesActionPerformed

        java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (ventana instanceof Inicio) {
            Inicio inicioFrame = (Inicio) ventana;
            inicioFrame.irAPanelLlaves();

        }
    }//GEN-LAST:event_btnGenerarLlavesActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int filaSeleccionada = tablaEquipos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String nombreEquipo = tablaEquipos.getValueAt(filaSeleccionada, 0).toString();
            int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de que deseas eliminar al equipo '" + nombreEquipo + "'?",
                    "Confirmar Eliminación",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            if (confirmar == javax.swing.JOptionPane.YES_OPTION) {

                com.utp.aed.proyectotorneo.dao.EquipoDAO dao = new com.utp.aed.proyectotorneo.dao.EquipoDAO();
                if (dao.eliminarPorNombre(nombreEquipo)) {

                    papeleraReciclaje.push(nombreEquipo);

                    javax.swing.JOptionPane.showMessageDialog(this, "Equipo enviado a la papelera.");
                    actualizarPantalla();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el equipo de la Base de Datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un equipo de la tabla para poder eliminarlo.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed
        if (!pilaDeshacer.estaVacia()) {
            // Extrae el último equipo ingresado (LIFO)
            String ultimoEquipo = pilaDeshacer.pop();

            com.utp.aed.proyectotorneo.dao.EquipoDAO dao = new com.utp.aed.proyectotorneo.dao.EquipoDAO();
            if (dao.eliminarPorNombre(ultimoEquipo)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Acción deshecha. Se eliminó el registro de: " + ultimoEquipo);
                actualizarPantalla();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay registros recientes para deshacer en esta sesión.");
        }
    }//GEN-LAST:event_btnDeshacerActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if (!papeleraReciclaje.estaVacia()) {
            String equipoARestaurar = papeleraReciclaje.pop();

            com.utp.aed.proyectotorneo.dao.EquipoDAO dao = new com.utp.aed.proyectotorneo.dao.EquipoDAO();
            if (dao.registrarEquipo(equipoARestaurar)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Se ha restaurado el equipo: " + equipoARestaurar);
                actualizarPantalla();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "La papelera está vacía.");
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed

        ArbolBinarioBusqueda arbolEquipos = new ArbolBinarioBusqueda();
        for (int i = 0; i < Inicio.listaEquipos.getTamano(); i++) {
            arbolEquipos.insertar(Inicio.listaEquipos.obtener(i));
        }
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaEquipos.getModel();
        modelo.setRowCount(0);
        arbolEquipos.llenarTablaEnOrden(arbolEquipos.raiz, modelo);

        javax.swing.JOptionPane.showMessageDialog(this, "Equipos ordenados");
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void txtNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEquipoActionPerformed
        // TODO add your handling code here:
        btnAgregar.doClick();
    }//GEN-LAST:event_txtNombreEquipoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        String nombre = txtNombreEquipo.getText().trim();
        if (!nombre.isEmpty()) {
            com.utp.aed.proyectotorneo.dao.EquipoDAO dao = new com.utp.aed.proyectotorneo.dao.EquipoDAO();
            if (dao.registrarEquipo(nombre)) {
                pilaDeshacer.push(nombre);
                txtNombreEquipo.setText("");
                txtNombreEquipo.requestFocus();
                actualizarPantalla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en Base de Datos. Puede que ya exista.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Escribe un nombre de equipo.");
        }
    }
    
    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas eliminar todos los equipos inscritos y reiniciar el torneo?",
                "Confirmar Reinicio",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirmacion == 0) {
            com.utp.aed.proyectotorneo.dao.EquipoDAO dao = new com.utp.aed.proyectotorneo.dao.EquipoDAO();
            dao.eliminarTodos();
            new com.utp.aed.proyectotorneo.dao.LlaveDAO().eliminarArbol();
            Inicio.campeonActual = "";
            actualizarPantalla();

            javax.swing.JOptionPane.showMessageDialog(this, "El torneo ha sido reiniciado en la Base de Datos.");
        }
    }

    class NodoPilaEquipo {

        String nombreEquipo;
        NodoPilaEquipo siguiente;

        public NodoPilaEquipo(String nombre) {
            this.nombreEquipo = nombre;
            this.siguiente = null;
        }
    }

    class PilaEquipos {

        NodoPilaEquipo cima;

        public void push(String nombre) {
            NodoPilaEquipo nuevo = new NodoPilaEquipo(nombre);
            nuevo.siguiente = cima;
            cima = nuevo;
        }

        public String pop() {
            if (cima == null) {
                return null;
            }
            String extraido = cima.nombreEquipo;
            cima = cima.siguiente;
            return extraido;
        }

        public boolean estaVacia() {
            return cima == null;
        }
    }

    class PilaPapelera {

        NodoPilaEquipo cima;

        public void push(String nombre) {
            NodoPilaEquipo nuevo = new NodoPilaEquipo(nombre);
            nuevo.siguiente = cima;
            cima = nuevo;
        }

        public String pop() {
            if (cima == null) {
                return null;
            }
            String extraido = cima.nombreEquipo;
            cima = cima.siguiente;
            return extraido;
        }

        public boolean estaVacia() {
            return cima == null;
        }
    }

    class NodoArbolEquipo {

        String nombreEquipo;
        NodoArbolEquipo izquierdo, derecho;

        public NodoArbolEquipo(String nombre) {
            this.nombreEquipo = nombre;
            izquierdo = derecho = null;
        }
    }

    class ArbolBinarioBusqueda {

        NodoArbolEquipo raiz;

        public ArbolBinarioBusqueda() {
            raiz = null;
        }

        public void insertar(String nombre) {
            raiz = insertarRecursivo(raiz, nombre);
        }

        private NodoArbolEquipo insertarRecursivo(NodoArbolEquipo nodo, String nombre) {
            if (nodo == null) {
                return new NodoArbolEquipo(nombre);
            }
            if (nombre.compareToIgnoreCase(nodo.nombreEquipo) < 0) {
                nodo.izquierdo = insertarRecursivo(nodo.izquierdo, nombre);
            } else if (nombre.compareToIgnoreCase(nodo.nombreEquipo) > 0) {
                nodo.derecho = insertarRecursivo(nodo.derecho, nombre);
            }
            return nodo;
        }

        public void llenarTablaEnOrden(NodoArbolEquipo nodo, javax.swing.table.DefaultTableModel modelo) {
            if (nodo != null) {
                llenarTablaEnOrden(nodo.izquierdo, modelo);
                modelo.addRow(new Object[]{nodo.nombreEquipo});
                llenarTablaEnOrden(nodo.derecho, modelo);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarLlaves;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalInscritos;
    private javax.swing.JTable tablaEquipos;
    private javax.swing.JTextField txtNombreEquipo;
    // End of variables declaration//GEN-END:variables
}
