/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utp.aed.proyectotorneo.view;

/**
 *
 * @author MSI
 */
public class PanelDashboard extends javax.swing.JPanel {

    private com.utp.aed.proyectotorneo.model.Usuario usuarioActual;

    public PanelDashboard() {
        initComponents();
        actualizarPantalla(); 
    }

    public PanelDashboard(com.utp.aed.proyectotorneo.model.Usuario usuario) {
        this.usuarioActual = usuario;
        initComponents();
        actualizarPantalla(); 
    }

    private void actualizarPantalla() {
        com.utp.aed.proyectotorneo.dao.EquipoDAO dao = new com.utp.aed.proyectotorneo.dao.EquipoDAO();
        if(Inicio.listaEquipos.isEmpty()){
            Inicio.listaEquipos = (java.util.ArrayList<String>) dao.obtenerTodosLosNombres();
        }

        int total = Inicio.listaEquipos.size();
        lblTotalEquipos.setText(String.valueOf(total));
        
        if (usuarioActual != null && "Equipo".equalsIgnoreCase(usuarioActual.getRol().getNombre())) {
            lblEstadoMotor.setText("Modo Observador");
            lblCampeon.setText(Inicio.campeonActual.isEmpty() ? "En curso" : Inicio.campeonActual);
            txtConsola.setText("¡Bienvenido, " + usuarioActual.getUsername() + "!\n");
            txtConsola.append("INFO: Tienes acceso de solo lectura al sistema.\n");
            txtConsola.append("INFO: Ve a 'Ver Torneo' y busca tu nombre en la barra de búsqueda para ver tu progreso.");
        } else {
            if (!Inicio.campeonActual.isEmpty()) {
                lblEstadoMotor.setText("Torneo Finalizado");
                lblCampeon.setText(Inicio.campeonActual);
                txtConsola.setText("INFO: Torneo concluido exitosamente.\nINFO: Renderizado del árbol completado.\nINFO: El campeón coronado es: " + Inicio.campeonActual);
            } else {
                lblCampeon.setText("No determinado");
                if (total == 0) {
                    lblEstadoMotor.setText("Esperando datos");
                    txtConsola.setText("INFO: Modelo inicializado.\nINFO: Árbol Binario Estricto listo para ser construido.\nINFO: Vaya al módulo 'Inscripción' para añadir equipos.");
                } else if (total == 1) {
                    lblEstadoMotor.setText("Faltan equipos");
                    txtConsola.setText("INFO: 1 equipo detectado en memoria.\nWARNING: Se requiere al menos 2 equipos para iniciar un torneo.");
                } else {
                    lblEstadoMotor.setText("Listo para simular");
                    txtConsola.setText("INFO: " + total + " equipos detectados en memoria.\nINFO: Módulo de llaves preparado para renderizar el árbol.\nINFO: Puede proceder a generar los emparejamientos.");
                }
            }
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jlabel2 = new javax.swing.JLabel();
        lblEstadoMotor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        lblCampeon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlabel = new javax.swing.JLabel();
        lblTotalEquipos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(30, 30, 30));

        jPanel3.setBackground(new java.awt.Color(37, 37, 38));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 45, 45), 5, true));

        jlabel2.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel2.setText("Estado");

        lblEstadoMotor.setBackground(new java.awt.Color(255, 255, 255));
        lblEstadoMotor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstadoMotor.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoMotor.setText("Esperando datos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEstadoMotor))
                    .addComponent(jlabel2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstadoMotor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(37, 37, 38));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 45, 45), 5, true));

        jlabel1.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 255, 255));
        jlabel1.setText("Campeon");

        lblCampeon.setBackground(new java.awt.Color(255, 255, 255));
        lblCampeon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCampeon.setForeground(new java.awt.Color(255, 153, 0));
        lblCampeon.setText("No determinado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCampeon))
                    .addComponent(jlabel1))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCampeon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(37, 37, 38));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 45, 45), 5, true));

        jlabel.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setText("Equipos Inscritos");

        lblTotalEquipos.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalEquipos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotalEquipos.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalEquipos.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel)
                    .addComponent(lblTotalEquipos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalEquipos)
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(37, 37, 38));

        jLabel1.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO ");

        txtConsola.setEditable(false);
        txtConsola.setBackground(new java.awt.Color(37, 37, 38));
        txtConsola.setColumns(20);
        txtConsola.setForeground(new java.awt.Color(255, 255, 255));
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel lblCampeon;
    private javax.swing.JLabel lblEstadoMotor;
    private javax.swing.JLabel lblTotalEquipos;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables
}




