/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utp.aed.proyectotorneo.view;

/**
 *
 * @author MSI
 */
public class SeleccionDeporte extends javax.swing.JFrame {
    
    private com.utp.aed.proyectotorneo.model.Usuario usuarioActual;
    private ArbolNavegacion enrutador; // <-- Declaramos el árbol de navegación
    
    
    /**
     * Creates new form OPCIONES
     */
    public SeleccionDeporte() {
        initComponents();
        // 1. Lo hacemos un poco más grande que el Login (el login era 400x320)
        this.setSize(600, 400); 
        
        // 2. Lo centramos en la pantalla para que aparezca en la misma posición
        this.setLocationRelativeTo(null);
    }
    
    public SeleccionDeporte(com.utp.aed.proyectotorneo.model.Usuario usuario) {
        this(); 
        this.usuarioActual = usuario; 
        
        // Inicializamos el árbol pasándole esta ventana y el usuario
        this.enrutador = new ArbolNavegacion(this, this.usuarioActual);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFutbol = new javax.swing.JButton();
        btnVoley = new javax.swing.JButton();
        btnBasquet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Torneo - Selección de Deporte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFutbol.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFutbol.setForeground(new java.awt.Color(255, 255, 255));
        btnFutbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_Futbol1.png"))); // NOI18N
        btnFutbol.setText("FUTBOL");
        btnFutbol.setBorderPainted(false);
        btnFutbol.setContentAreaFilled(false);
        btnFutbol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFutbol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFutbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFutbolActionPerformed(evt);
            }
        });
        getContentPane().add(btnFutbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 120));

        btnVoley.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnVoley.setForeground(new java.awt.Color(255, 255, 255));
        btnVoley.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_Voley2.png"))); // NOI18N
        btnVoley.setText("VOLEY");
        btnVoley.setBorderPainted(false);
        btnVoley.setContentAreaFilled(false);
        btnVoley.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoley.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoleyActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoley, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, 120));

        btnBasquet.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBasquet.setForeground(new java.awt.Color(255, 255, 255));
        btnBasquet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_basquet (2).png"))); // NOI18N
        btnBasquet.setText("BASQUET");
        btnBasquet.setBorderPainted(false);
        btnBasquet.setContentAreaFilled(false);
        btnBasquet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBasquet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBasquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasquetActionPerformed(evt);
            }
        });
        getContentPane().add(btnBasquet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 130, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECCIONA DEPORTE A REALIZAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_seleccion.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFutbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFutbolActionPerformed
        // TODO add your handling code here:
        enrutador.navegarA("Futbol");
        
    }//GEN-LAST:event_btnFutbolActionPerformed

    private void btnVoleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoleyActionPerformed
        // TODO add your handling code here:
        enrutador.navegarA("Voley");
    }//GEN-LAST:event_btnVoleyActionPerformed

    private void btnBasquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasquetActionPerformed
        // TODO add your handling code here:
        enrutador.navegarA("Basquet");
    }//GEN-LAST:event_btnBasquetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionDeporte().setVisible(true);
            }
        });
    }
    // =====================================================================
    // ESTRUCTURA DE DATOS: ÁRBOL N-ARIO (ÁRBOL GENERAL) PARA NAVEGACIÓN
    // =====================================================================
    class NodoRuta {
        String nombreModulo;
        java.util.List<NodoRuta> subModulos; // Permite múltiples hijos (N-ario)

        public NodoRuta(String nombreModulo) {
            this.nombreModulo = nombreModulo;
            this.subModulos = new java.util.ArrayList<>();
        }

        public void agregarSubRuta(NodoRuta hijo) {
            subModulos.add(hijo);
        }
    }

    class ArbolNavegacion {
        NodoRuta raiz;
        javax.swing.JFrame ventanaActual;
        com.utp.aed.proyectotorneo.model.Usuario usuarioActivo;

        public ArbolNavegacion(javax.swing.JFrame ventanaActual, com.utp.aed.proyectotorneo.model.Usuario usuarioActivo) {
            this.ventanaActual = ventanaActual;
            this.usuarioActivo = usuarioActivo;
            
            // Construimos el árbol de rutas en memoria
            raiz = new NodoRuta("SeleccionDeporte");
            
            NodoRuta nodoFutbol = new NodoRuta("Futbol");
            NodoRuta nodoVoley = new NodoRuta("Voley");
            NodoRuta nodoBasquet = new NodoRuta("Basquet");
            
            raiz.agregarSubRuta(nodoFutbol);
            raiz.agregarSubRuta(nodoVoley);
            raiz.agregarSubRuta(nodoBasquet);
        }

        // Método que recorre el árbol para ejecutar la acción correcta
        public void navegarA(String destino) {
            boolean rutaEncontrada = buscarYEjecutarRuta(raiz, destino);
            
            if (!rutaEncontrada) {
                javax.swing.JOptionPane.showMessageDialog(ventanaActual, 
                    "Error de enrutamiento: Nodo no encontrado en el Árbol de Navegación.", 
                    "Error 404", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

        private boolean buscarYEjecutarRuta(NodoRuta nodoActual, String destino) {
            if (nodoActual == null) return false;

            // Si encontramos el nodo destino en el árbol, ejecutamos la apertura de ventana
            if (nodoActual.nombreModulo.equalsIgnoreCase(destino)) {
                
                if (destino.equals("Futbol")) {
                    Inicio ventanaTorneo = new Inicio(usuarioActivo);
                    ventanaTorneo.setVisible(true);
                    ventanaActual.dispose(); // Cierra el menú actual
                } 
                else if (destino.equals("Voley") || destino.equals("Basquet")) {
                    javax.swing.JOptionPane.showMessageDialog(ventanaActual, 
                        "El módulo de " + destino + " se encuentra en fase de desarrollo.", 
                        "Próximamente", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                return true;
            }

            // Búsqueda recursiva en los hijos (N-ario)
            for (NodoRuta hijo : nodoActual.subModulos) {
                if (buscarYEjecutarRuta(hijo, destino)) {
                    return true;
                }
            }
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBasquet;
    private javax.swing.JButton btnFutbol;
    private javax.swing.JButton btnVoley;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
