/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utp.aed.proyectotorneo.view;

/**
 *
 * @author MSI
 */
public class SeleccionDeporte extends javax.swing.JFrame {
    
    private com.utp.aed.proyectotorneo.model.Usuario usuarioActual;
    private ArbolNavegacionBinario enrutador;
    
    public SeleccionDeporte() {
        initComponents();
        this.setSize(600, 400); 
        this.setLocationRelativeTo(null);
        
    }
    
    public SeleccionDeporte(com.utp.aed.proyectotorneo.model.Usuario usuario) {
        this(); 
        this.usuarioActual = usuario; 
        this.enrutador = new ArbolNavegacionBinario(this, this.usuarioActual);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFutbol = new javax.swing.JButton();
        btnVoley = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Torneo - Selección de Deporte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFutbol.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFutbol.setForeground(new java.awt.Color(255, 255, 255));
        btnFutbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_Futbol1.png"))); // NOI18N
        btnFutbol.setText("FUTBOL");
        btnFutbol.setBorderPainted(false);
        btnFutbol.setContentAreaFilled(false);
        btnFutbol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFutbol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFutbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFutbolActionPerformed(evt);
            }
        });
        getContentPane().add(btnFutbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, 120));

        btnVoley.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnVoley.setForeground(new java.awt.Color(255, 255, 255));
        btnVoley.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_Voley2.png"))); // NOI18N
        btnVoley.setText("VOLEY");
        btnVoley.setBorderPainted(false);
        btnVoley.setContentAreaFilled(false);
        btnVoley.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoley.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoleyActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoley, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 130, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECCIONA DEPORTE A REALIZAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_seleccion.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFutbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFutbolActionPerformed
        // TODO add your handling code here:
        enrutador.navegarA("Futbol");
        
    }//GEN-LAST:event_btnFutbolActionPerformed

    private void btnVoleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoleyActionPerformed
        // TODO add your handling code here:
        enrutador.navegarA("Voley");
    }//GEN-LAST:event_btnVoleyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionDeporte().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFutbol;
    private javax.swing.JButton btnVoley;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    class NodoRutaBinario {
        String nombreModulo;
        NodoRutaBinario izquierdo; 
        NodoRutaBinario derecho;
        
        public NodoRutaBinario(String nombreModulo) {
            this.nombreModulo = nombreModulo;
            this.izquierdo = null;
            this.derecho = null;
        }
    }

    class ArbolNavegacionBinario {
        NodoRutaBinario raiz;
        javax.swing.JFrame ventanaActual;
        com.utp.aed.proyectotorneo.model.Usuario usuarioActivo;

        public ArbolNavegacionBinario(javax.swing.JFrame ventanaActual, com.utp.aed.proyectotorneo.model.Usuario usuarioActivo) {
            this.ventanaActual = ventanaActual;
            this.usuarioActivo = usuarioActivo;
            raiz = new NodoRutaBinario("SeleccionDeporte");
            raiz.izquierdo = new NodoRutaBinario("Futbol");
            raiz.derecho = new NodoRutaBinario("Voley");
        }

        public void navegarA(String destino) {
            boolean rutaEncontrada = buscarYEjecutarRuta(raiz, destino);
            
            if (!rutaEncontrada) {
                javax.swing.JOptionPane.showMessageDialog(ventanaActual, 
                    "Error de enrutamiento.", 
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

        private boolean buscarYEjecutarRuta(NodoRutaBinario nodoActual, String destino) {
            
            if (nodoActual == null) return false;
            if (nodoActual.nombreModulo.equalsIgnoreCase(destino)) {
                
                if (destino.equals("Futbol")) {
                    Inicio ventanaTorneo = new Inicio(usuarioActivo);
                    ventanaTorneo.setVisible(true);
                    ventanaActual.dispose();
                } 
                else if (destino.equals("Voley")) {
                    javax.swing.JOptionPane.showMessageDialog(ventanaActual, 
                        "El módulo de Voley se encuentra en fase de diseño estructural.", 
                        "En Desarrollo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                return true;
            }
            boolean encontradoIzquierda = buscarYEjecutarRuta(nodoActual.izquierdo, destino);
            if (encontradoIzquierda) {
                return true;
            }
            return buscarYEjecutarRuta(nodoActual.derecho, destino);
        }
    }

}
