/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utp.aed.proyectotorneo.view;

/**
 *
 * @author MSI
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public Splash() {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar en pantalla
        this.setBackground(new java.awt.Color(0, 0, 0, 0)); // Hace el fondo del JFrame 100% transparente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPorcentaje = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblPorcentaje.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblPorcentaje.setText("0%");

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/splash.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFondo)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentaje))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // 1. Iniciamos la pantalla de carga
        Splash splash = new Splash();
        splash.setVisible(true);

        try {
            // 2. Iniciamos el bucle del 0 al 100
            for (int i = 0; i <= 100; i++) {
                
                // Pausa de 30 milisegundos por cada número (puedes subirlo para que tarde más)
                Thread.sleep(30); 
                
                // Actualizamos la interfaz gráfica
                splash.lblPorcentaje.setText(i + "%");
                splash.barraProgreso.setValue(i);
                
                // 3. Cuando llega a 100, hacemos la transición
                if (i == 100) {
                    splash.dispose(); // Destruimos la pantalla de carga
                    LoginJFrame login = new LoginJFrame(); // Instanciamos tu Login
                    login.setVisible(true); // Mostramos el Login
                }
            }
        } catch (InterruptedException e) {
            System.out.println("Error en el hilo de carga: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPorcentaje;
    // End of variables declaration//GEN-END:variables
}
